module Web.Chione where


-- | 'Build' is the various ways of building a final page.

data Build = FromContent        -- ^ from content directory
           | AutoGenerated      -- ^ HTML generated somehow (sitemap, reference pages, etc)
           | Redirect           -- ^ simple redirect (need to look up table to avoid rebuilding)
           | Copy               -- ^ copy from root of repo (gif, css, etc)
           deriving (Show, Read, Eq, Ord)

